### PR TITLE
Show captions on embedded videos

### LINKED ISSUE #6: Force closed captioning on embedded youtube videos
I believe this is possible, as described [here](https://support.automaticsync.com/hc/en-us/articles/115002362403-How-to-force-Closed-Captions-to-appear-on-YouTube-videos-you-own)

Edits needed would be by editing the embed code: open the video on a separate tab, click Share (under the video), and open the Embed section. Copy the embed code and add ?cc_load_policy=1 at the end of the URL

### PR DESCRIPTION
**Pull request by tsalo**
Closes #6. 

Changes proposed:
- Add `?cc_load_policy=1` to all embedded video URLs in order to automatically show captions.

### CODE REVIEW

**Comment by tsalo** [comment]
I did some local testing and it seems to be working.

@jessicabartley neither of the Q&A sessions have captions. I figured it would take time for Youtube to build them for Week 2, but I'm a little surprised they're missing from Week 1. Is that expected?

**Review by jessicabartley — CHANGES_REQUESTED** [review]
Looks good except I think (but am not certain) that the additions need to actually be "cc_load_policy=1&cc_lang_pref=en" to specify the cc language

see https://stackoverflow.com/questions/41239654/embed-youtube-with-captions-on-by-default-not-working

**Comment by tsalo** [comment]
Ah, okay. Thanks for catching that! I've updated the file and the videos look good locally, so I'll request another round of review.

**Review by jessicabartley — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
