### PR TITLE
Add resources page

### LINKED ISSUE #18: Add page with container access information
Could call the page "Resources" with links to a range of Google Docs. Pinging @satra and @angielaird about structure and content. I can handle adding the page.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #18. I still need to figure out content and formatting.

Changes proposed:
- Add new page (resources) with links to useful resources.
- Add new page to sidebar as well.
- Some new CSS classes to handle formatting for the sidebar and resources page.

### CODE REVIEW

**Comment by tsalo** [comment]
Here's what we're looking at right now. @angielaird WDYT?

image

**Comment by angielaird** [comment]
omg is that comic sans? 😱

**Comment by tsalo** [comment]
Yes bc I'm classy.

**Comment by angielaird** [comment]
Then I think you should include disclaimer at the bottom that says "Website fonts selected by Taylor Salo who is going on the job market in 2021".

**Comment by tsalo** [comment]
🤣 touché! I think I'll have to wait for tenure before I can publicly admit my love for Comic Sans.

**Comment by dmoracze** [comment]
+1 on Comic Sans 😬

**Comment by angielaird** [comment]
@tsalo there is such a thing as post-tenure review so you might want to keep your love for CS on the DL permanently

@dmoracze you might be the first person in history to be +1 for CS 😂

**Comment by tsalo** [comment]
How does this look?
image

**Comment by dmoracze** [comment]
What about some of the resources for Windows users (from the [Neurostars](https://neurostars.org/t/installing-shell-git-on-windows/17200/2) thread)?

https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:regionofsystemrequirementstab
https://gitforwindows.org/

**Comment by tsalo** [comment]
I'll add a section. Thanks @dmoracze!

**Comment by tsalo** [comment]
Merging now. We can update further in separate PRs.

**Pull request merged**
